param(
    # Icon to embed. Defaults to icon.ico beside this script if present.
    [string]$Icon
)

$ErrorActionPreference = "Stop"

<#
Test-SMTP build script

Dependencies (required on build machine)

Python
- Python 3 (64-bit), on PATH as 'python' or via the 'py' launcher

Python packages
- pyinstaller (current release; installed automatically below)

Output
- Final distributable:
    dist\Test-SMTP.exe

- Single self-contained executable (PyInstaller onefile)
- No external dependencies required on target system

Notes
- Build on Windows. PyInstaller is not a cross-compiler.
- Console app (--console); do not build windowed.
- No .spec file: PyInstaller is driven directly from the flags below so
  there is one fewer file to keep in sync. icon.ico is embedded if present.
- No version_info.txt either: the Windows version resource is generated below
  from __version__ in Test-SMTP.py, so there is only one place to bump.
#>

# -- Paths ---------------------------------------------------------------------
$scriptDir = $PSScriptRoot
$source    = Join-Path $scriptDir "Test-SMTP.py"
$verFile   = Join-Path ([System.IO.Path]::GetTempPath()) "Test-SMTP.version.txt"

# Icon: -Icon arg wins, else icon.ico beside the script if it exists.
$iconFile = if ($Icon) { $Icon } else { Join-Path $scriptDir "icon.ico" }
if ($Icon -and -not (Test-Path $iconFile)) { throw "Icon not found: $iconFile" }

# Python (prefer 'python', fall back to the 'py' launcher)
$py = $null
foreach ($candidate in @("python", "py")) {
    if (Get-Command $candidate -ErrorAction SilentlyContinue) { $py = $candidate; break }
}
if (-not $py) { throw "Python 3 not found on PATH" }

$pyBits = & $py "-c" "import struct; print(struct.calcsize('P') * 8)"
if ($pyBits -ne "64") {
    Write-Warning "Python at '$py' is $pyBits-bit. The EXE will match; build with 64-bit for current fleets."
}

# Output
$distDir   = Join-Path $scriptDir "dist"
$outputExe = Join-Path $distDir "Test-SMTP.exe"

# -- Clean ---------------------------------------------------------------------
Remove-Item $distDir -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path $distDir -Force | Out-Null

# -- Version resource ----------------------------------------------------------
# Single source of truth is __version__ in Test-SMTP.py; the .exe file
# properties are generated from it so the two cannot drift.
$match = [regex]::Match((Get-Content $source -Raw), '(?m)^__version__\s*=\s*"([^"]+)"')
if (-not $match.Success) { throw "Could not find __version__ in $source" }
$version = $match.Groups[1].Value

# Windows wants a 4-part numeric version; pad short ones like "1.1.0".
$quad = (@($version -split '\.') + @('0', '0', '0', '0'))[0..3]
foreach ($part in $quad) {
    if ($part -notmatch '^\d+$') {
        throw "__version__ '$version' is not numeric; Windows version resources cannot express it."
    }
}
$tuple  = $quad -join ', '
$dotted = $quad -join '.'
$year   = (Get-Date).Year

Set-Content -Path $verFile -Encoding UTF8 -Value @"
# UTF-8
# Generated by build.ps1 from __version__ in Test-SMTP.py. Do not edit.

VSVersionInfo(
    ffi=FixedFileInfo(
        filevers=($tuple),
        prodvers=($tuple),
        mask=0x3f,
        flags=0x0,
        OS=0x40004,
        fileType=0x1,
        subtype=0x0,
        date=(0, 0)
    ),
    kids=[
        StringFileInfo(
            [
                StringTable(
                    '040904B0',
                    [
                        StringStruct('CompanyName', 'asheroto'),
                        StringStruct('FileDescription', 'SMTP Connection Tester'),
                        StringStruct('FileVersion', '$dotted'),
                        StringStruct('InternalName', 'Test-SMTP'),
                        StringStruct('LegalCopyright', 'Copyright (c) $year asheroto'),
                        StringStruct('OriginalFilename', 'Test-SMTP.exe'),
                        StringStruct('ProductName', 'SMTP Connection Tester'),
                        StringStruct('ProductVersion', '$dotted')
                    ]
                )
            ]
        ),
        VarFileInfo([VarStruct('Translation', [1033, 1200])])
    ]
)
"@

Write-Output "Building Test-SMTP $dotted"

# -- Install deps --------------------------------------------------------------
& $py "-m" "pip" "install" "--upgrade" "pyinstaller"
if ($LASTEXITCODE -ne 0) { throw "pyinstaller install failed" }

# -- Build EXE -----------------------------------------------------------------
$pyiArgs = @(
    "-m", "PyInstaller",
    "--clean", "--noconfirm",
    "--onefile", "--console",
    "--name", "Test-SMTP",
    "--version-file", $verFile,
    # Stdlib modules PyInstaller auto-pulls but this script never uses. Trims a
    # couple MB. Safe given the imports (os/ssl/smtplib/socket/argparse/email).
    "--exclude-module", "tkinter",
    "--exclude-module", "unittest",
    "--exclude-module", "pydoc",
    "--exclude-module", "lib2to3",
    "--exclude-module", "test"
)
if (Test-Path $iconFile) { $pyiArgs += @("--icon", $iconFile) }
$pyiArgs += $source

& $py @pyiArgs
if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed" }

if (-not (Test-Path $outputExe)) {
    throw "EXE not found after build: $outputExe"
}

Write-Output "Done: $outputExe"
